import os
import sys
import ctypes
import csv
import logging
import argparse
import traceback
import ipaddress
import urllib.request
import urllib.error
from datetime import datetime

IP_LIST_FILE = "IPs.txt"
HTML_REPORT_FILE = "report_IPTor0x.html"
CSV_REPORT_FILE = "report_IPTor0x.csv"
LOG_FILE = "iptor0x.log"
TOR_EXIT_LIST_URL = "https://check.torproject.org/torbulkexitlist"

logger = logging.getLogger("IPTor0x")

# --- ANSI color support (replaces colorama) ---
RESET = "\x1b[0m"
BRIGHT = "\x1b[1m"
CYAN = "\x1b[36m"
RED = "\x1b[31m"
GREEN = "\x1b[32m"
YELLOW = "\x1b[33m"
LIGHTBLUE = "\x1b[94m"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Check a list of IPs against the official TOR exit node list."
    )
    parser.add_argument(
        "-i", "--input",
        default=IP_LIST_FILE,
        metavar="FILE",
        help=f"Path to the file with one IP per line (default: {IP_LIST_FILE}).",
    )
    parser.add_argument(
        "--log",
        action="store_true",
        help=f"Write a detailed run log to {LOG_FILE} (disabled by default).",
    )
    parser.add_argument(
        "--no-report",
        action="store_true",
        help=f"Skip generating {HTML_REPORT_FILE} and {CSV_REPORT_FILE} (both are generated by default).",
    )
    return parser.parse_args()


def setup_logging(enable_log_file):
    """Configures file logging so runs can be audited later, only if requested."""
    logger.setLevel(logging.INFO)
    if enable_log_file:
        handler = logging.FileHandler(LOG_FILE, encoding="utf-8")
        handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))
        logger.addHandler(handler)
    else:
        logger.addHandler(logging.NullHandler())
    logger.propagate = False


def enable_ansi_colors():
    """Enables ANSI escape sequence processing on Windows consoles."""
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except AttributeError:
        pass
    if sys.platform == "win32":
        kernel32 = ctypes.windll.kernel32
        handle = kernel32.GetStdHandle(-11)  # STD_OUTPUT_HANDLE
        mode = ctypes.c_uint32()
        if kernel32.GetConsoleMode(handle, ctypes.byref(mode)):
            kernel32.SetConsoleMode(handle, mode.value | 0x0004)  # ENABLE_VIRTUAL_TERMINAL_PROCESSING


# Application logo
def print_logo():
    logo = r"""
██╗██████╗ ████████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗
██║██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗██╔═████╗╚██╗██╔╝
██║██████╔╝   ██║   ██║   ██║██████╔╝██║██╔██║ ╚███╔╝
██║██╔═══╝    ██║   ██║   ██║██╔══██╗████╔╝██║ ██╔██╗
██║██║        ██║   ╚██████╔╝██║  ██║╚██████╔╝██╔╝ ██╗
╚═╝╚═╝        ╚═╝    ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═
    by corvus0x

    """
    print(CYAN + logo + RESET)


class TorListUnavailableError(Exception):
    """Raised when the official TOR exit node list cannot be downloaded."""


def get_tor_exit_nodes():
    """Downloads the list of TOR exit nodes from the official site."""
    try:
        with urllib.request.urlopen(TOR_EXIT_LIST_URL, timeout=10) as response:
            if response.status != 200:
                raise TorListUnavailableError(f"Unexpected HTTP status {response.status}")
            return set(response.read().decode("utf-8").splitlines())
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        raise TorListUnavailableError(str(exc)) from exc


def load_ip_list(file_path):
    """Loads and validates the list of IPs from a file.

    Returns a tuple (valid_ips, invalid_lines). Invalid or duplicate
    lines are skipped (and logged) rather than crashing the run.
    """
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            raw_lines = [line.strip() for line in f if line.strip()]
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            f"Input file '{file_path}' was not found. Create it with one IP per line."
        ) from exc

    valid_ips = []
    invalid_lines = []
    seen = set()
    for line in raw_lines:
        try:
            ipaddress.ip_address(line)
        except ValueError:
            invalid_lines.append(line)
            logger.warning("Skipping invalid IP entry: %r", line)
            continue
        if line in seen:
            logger.info("Skipping duplicate IP entry: %s", line)
            continue
        seen.add(line)
        valid_ips.append(line)

    if not valid_ips:
        raise ValueError(f"No valid IP addresses found in '{file_path}'.")

    return valid_ips, invalid_lines


def check_ip(ip, tor_exit_nodes):
    """Checks if an IP is in the TOR exit node list."""
    return ip if ip in tor_exit_nodes else None


def generate_html_report(tor_ips, non_tor_ips, invalid_lines, total_ips, generated_at):
    """Generates an HTML report with the results."""
    tor_count = len(tor_ips)
    tor_percentage = round((tor_count / total_ips) * 100, 2) if total_ips > 0 else 0

    tor_rows = "\n".join(
        f'                    <tr class="tor-node">\n'
        f'                        <td>{ip}</td>\n'
        f'                        <td><a href="https://www.abuseipdb.com/check/{ip}" target="_blank">View Info</a></td>\n'
        f'                    </tr>'
        for ip in tor_ips
    )
    tor_empty_row = '                    <tr><td colspan="2">No TOR exit nodes detected.</td></tr>' if not tor_ips else ""

    non_tor_rows = "\n".join(
        f'                    <tr>\n'
        f'                        <td>{ip}</td>\n'
        f'                    </tr>'
        for ip in non_tor_ips
    )
    non_tor_empty_row = '                    <tr><td>No IPs in this category.</td></tr>' if not non_tor_ips else ""

    if invalid_lines:
        invalid_rows = "\n".join(
            f'                    <tr>\n'
            f'                        <td>{line}</td>\n'
            f'                    </tr>'
            for line in invalid_lines
        )
        invalid_section = f"""
        <div class="invalid-section">
            <h2>Ignored invalid or malformed entries</h2>
            <table class="invalid-table">
                <tr><th>Original entry</th></tr>
{invalid_rows}
            </table>
        </div>
"""
    else:
        invalid_section = ""

    html_content = f"""
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>IPTor0x Report</title>
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 0;
                padding: 20px;
                background-color: #f4f4f9;
                color: #333;
            }}
            h1 {{
                color: #444;
                text-align: center;
                margin-top: 20px;
                font-size: 48px;
                font-weight: 900;
            }}
            h1::after {{
                content: '';
                display: block;
                width: 50px;
                margin: 10px auto;
                border-bottom: 3px solid #444;
            }}
            h2 {{
                color: #333;
                margin-top: 30px;
                font-size: 24px;
                padding: 10px;
            }}
            .info-section, .tor-section, .non-tor-section, .invalid-section {{
                width: 90%;
                margin: 30px auto;
                padding: 15px;
                border-radius: 8px;
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
                background-color: white;
            }}
            .info-section {{
                background-color: #f8f9fa;
                border-left: 5px solid #007bff;
            }}
            .tor-section {{
                border-left: 5px solid #dc3545;
            }}
            .non-tor-section {{
                border-left: 5px solid #28a745;
            }}
            .invalid-section {{
                border-left: 5px solid #ffc107;
            }}
            .search-box {{
                width: 100%;
                box-sizing: border-box;
                padding: 8px 12px;
                margin-top: 15px;
                border: 1px solid #ccc;
                border-radius: 6px;
                font-size: 14px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
                box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            }}
            th, td {{
                border: 1px solid #ddd;
                padding: 7px;
                text-align: center;
            }}
            .tor-table th {{
                background-color: rgba(220, 53, 69, 0.2);
                color: #000;
                font-size: 18px;
            }}
            .non-tor-table th {{
                background-color: rgba(40, 167, 69, 0.2);
                color: #000;
                font-size: 18px;
            }}
            .invalid-table th {{
                background-color: rgba(255, 193, 7, 0.25);
                color: #000;
                font-size: 18px;
            }}
            td {{
                font-size: 16px;
                color: #000;
            }}
            .tor-node {{
                background-color: transparent;
                font-weight: bold;
            }}
            .tor-node a {{
                background: linear-gradient(45deg, #AEC6CF, #b0b0b0); /* Pastel gray gradient */
                color: white;
                padding: 5px 10px;
                border-radius: 5px;
                text-decoration: none;
                font-size: 14px;
                display: inline-block;
                transition: background 0.3s ease-in-out;
            }}

            .tor-node a:hover {{
                background: linear-gradient(45deg, #b0b0b0, #8c8c8c); /* Darker pastel gray on hover */
            }}

            @media (max-width: 600px) {{
                h1 {{ font-size: 32px; }}
                .info-section, .tor-section, .non-tor-section, .invalid-section {{
                    width: 100%;
                    margin: 15px auto;
                    border-radius: 0;
                }}
                th, td {{ font-size: 13px; padding: 5px; }}
            }}

        </style>
    </head>
    <body>
        <h1>IPTor0x Report</h1>

        <div class="info-section">
            <h2>General Information</h2>
            <p><strong>Generated at:</strong> {generated_at}</p>
            <p><strong>Total IPs analyzed:</strong> {total_ips}</p>
            <p><strong>Total IPs that are TOR nodes:</strong> {tor_count}</p>
            <p><strong>Percentage of IPs that are TOR nodes:</strong> {tor_percentage}%</p>
        </div>

        <div class="tor-section">
            <h2>IPs detected as TOR nodes</h2>
            <input type="text" class="search-box" placeholder="Filter IPs..." oninput="filterTable(this, 'tor-table')">
            <table class="tor-table" id="tor-table">
                <tr><th>IP</th><th>AbuseIPDB</th></tr>
{tor_rows}
{tor_empty_row}
            </table>
        </div>

        <div class="non-tor-section">
            <h2>IPs that are not TOR nodes</h2>
            <input type="text" class="search-box" placeholder="Filter IPs..." oninput="filterTable(this, 'non-tor-table')">
            <table class="non-tor-table" id="non-tor-table">
                <tr><th>IP</th></tr>
{non_tor_rows}
{non_tor_empty_row}
            </table>
        </div>
{invalid_section}
        <script>
            function filterTable(input, tableId) {{
                const filter = input.value.trim().toLowerCase();
                const table = document.getElementById(tableId);
                const rows = table.getElementsByTagName('tr');
                for (let i = 1; i < rows.length; i++) {{
                    const cell = rows[i].getElementsByTagName('td')[0];
                    if (!cell) continue;
                    const text = cell.textContent || cell.innerText;
                    rows[i].style.display = text.toLowerCase().includes(filter) ? '' : 'none';
                }}
            }}
        </script>
    </body>
    </html>
    """

    with open(HTML_REPORT_FILE, "w", encoding="utf-8") as f:
        f.write(html_content)
        f.flush()
        os.fsync(f.fileno())


def generate_csv_report(tor_ips, non_tor_ips):
    """Generates a CSV report with one row per analyzed IP."""
    with open(CSV_REPORT_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["ip", "is_tor_exit_node"])
        for ip in tor_ips:
            writer.writerow([ip, True])
        for ip in non_tor_ips:
            writer.writerow([ip, False])
        f.flush()
        os.fsync(f.fileno())


def main(args):
    enable_ansi_colors()
    setup_logging(args.log)
    print_logo()
    logger.info("Run started")

    try:
        ip_list, invalid_lines = load_ip_list(args.input)
    except (FileNotFoundError, ValueError) as exc:
        logger.error("Failed to load IP list: %s", exc)
        print(RED + BRIGHT + f"[ERROR] {exc}" + RESET)
        sys.exit(1)

    if invalid_lines:
        details = f" (see {LOG_FILE} for details)" if args.log else " (rerun with --log for details)"
        print(YELLOW + f"[WARNING] Ignored {len(invalid_lines)} invalid entr"
              f"{'y' if len(invalid_lines) == 1 else 'ies'} in {args.input}"
              f"{details}." + RESET)

    try:
        tor_exit_nodes = get_tor_exit_nodes()
    except TorListUnavailableError as exc:
        logger.error("Could not download TOR exit node list: %s", exc)
        print(RED + BRIGHT + "[ERROR] Could not download the TOR exit node list "
              f"({exc}). Aborting to avoid producing a misleading report." + RESET)
        sys.exit(1)

    tor_ips = []
    non_tor_ips = []

    for ip in ip_list:
        if check_ip(ip, tor_exit_nodes):
            tor_ips.append(ip)
        else:
            non_tor_ips.append(ip)

    if tor_ips:
        print(YELLOW + BRIGHT + "The following IPs are TOR exit nodes:")
        for ip in tor_ips:
            print(RED + BRIGHT + f"{ip}")
        print(RESET)
    else:
        print(GREEN + BRIGHT + "No IPs found that are TOR exit nodes." + RESET)

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if args.no_report:
        logger.info("Skipping report generation (--no-report)")
    else:
        try:
            generate_html_report(tor_ips, non_tor_ips, invalid_lines, len(ip_list), generated_at)
            generate_csv_report(tor_ips, non_tor_ips)
        except OSError as exc:
            logger.error("Failed to write report files: %s", exc)
            print(RED + BRIGHT + f"[ERROR] Failed to write report files: {exc}" + RESET)
            sys.exit(1)

    logger.info(
        "Run finished: %d analyzed, %d TOR nodes, %d invalid entries",
        len(ip_list), len(tor_ips), len(invalid_lines),
    )
    if args.no_report:
        print(CYAN + BRIGHT + "[INFO] Report generation skipped (--no-report)." + RESET)
    else:
        print(CYAN + BRIGHT + "[INFO] Reports generated: " + LIGHTBLUE +
              f"{HTML_REPORT_FILE}, {CSV_REPORT_FILE}" + RESET)


if __name__ == "__main__":
    cli_args = parse_args()
    try:
        main(cli_args)
    except Exception:
        logger.exception("Unexpected error")
        if cli_args.log:
            print(RED + BRIGHT + f"[ERROR] An unexpected error occurred. Check {LOG_FILE} for details." + RESET)
        else:
            traceback.print_exc()
            print(RED + BRIGHT + "[ERROR] An unexpected error occurred (see traceback above)." + RESET)
        sys.exit(1)
